### PR TITLE
Updated the graph legend

### PR DESCRIPTION
**Pull request by MauriceHendrix**
@mirams suggested a change to the graph legends.
**Before the change:**
image

**Now it looks like:**
image

(these graphs aren't exactly 100% the same, but it shows the principle)

### CODE REVIEW

**Comment by MichaelClerx** [comment]
How did this get to 37 commits? And what is the change? I can see the difference, but what's the reasoning?

**Comment by MauriceHendrix** [comment]
> How did this get to 37 commits? And what is the change? I can see the difference, but what's the reasoning?

it should be 1 commit only 2 files changed, not wure what's happened there!

**Review by MichaelClerx — APPROVED** [review]
It looks OK but I don't really know :D

**Comment by MichaelClerx** [comment]
@MauriceHendrix does this address #412 and/or #413 ?

**Comment by MauriceHendrix** [comment]
@MichaelClerx I don't think it does I think it's just a layout update.

**Comment by MauriceHendrix** [comment]
> The 'Reset Zoom' and 'Toggle Legend' probably want to stay as the first thing next to the graph (with loads of groups the toggle legend button might disappear to where it is not clickable unless you have already toggled the legend!)

Really? I thought that would be confusing since those buttons relate to the individual models and not the groups?

**Comment by mirams** [comment]
The 'Reset zoom' button is purely to do with the graph? I don't know exactly how the toggle legend button works, but I thought it was just "show all the legend entries (for groups, individual lines, etc.)" versus "cut it off after so many pixels" and I was worried that "so many pixels" might end up less than the size of the model groups area!

**Comment by MauriceHendrix** [comment]
> The 'Reset zoom' button is purely to do with the graph? I don't know exactly how the toggle legend button works, but I thought it was just "show all the legend entries (for groups, individual lines, etc.)" versus "cut it off after so many pixels" and I was worried that "so many pixels" might end up less than the size of the model groups area!

true for the reset. the toggle works just on the individual models below it doesn't do anything with the groups above.

**Pull request closed without merging**
