### PR TITLE
Changed sub menu css to stop overlay

### PR DESCRIPTION
**Pull request by sroderick-g5sro**
Fixes: #318

### CODE REVIEW

**Review by jonc125 — CHANGES_REQUESTED** [review]
This isn't working for me on either Firefox or Chrome, despite confirming that gulp has re-generated style.css and the browser is loading the new version. I wonder whether the CSS change needs to be applied to the `ul` element inside `.navbar-submenu`?

**Comment by sroderick-g5sro** [comment]
Odd it seems to be working for me as below: 

image

image

**Comment by jonc125** [comment]
Ah, OK. So it's on top of the notifications pane for instance, but because the menu background is transparent it's still hard to read, particularly for the 'on top of entity name' case. Is it possible to tweak the background settings so we get the submenu in a solid plane white box?

**Comment by sroderick-g5sro** [comment]
I have added an white background to each menu but the text "fitting specification" falls outside as shown below: I have tried making the list boxes wider but as the title of each is centred it looks strange and disconnected. So we can either live with the last bit of "specifications" being outside a white background. Or perhaps shorten the text to "fitting specs"?

image

**Comment by jonc125** [comment]
I'd be inclined to go with the shorter text option I think.

**Review by jonc125 — APPROVED** [review]
Looks great!

**Pull request merged**
