### PR TITLE
Plotting improvements for fitting results

### PR DESCRIPTION
**Pull request by MichaelClerx**
Not for merging!

See https://github.com/ModellingWebLab/deployment/pull/20

Main changes:

- [x] Allow CSV files containing labels for graphs
- [x] Add histogram plotting code

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Histogram plotting? https://github.com/ModellingWebLab/fcweb/commit/fa548f9e0c58efb9456c7183baf7d41535655282

**Comment by jonc125** [comment]
I reckon we do want to merge this, once histograms are added.

The question will be whether to include the fake fitting & dataset handling here instead of just in fc-runner, as a move towards how we'll approach this eventually. I think it'd be nice to do so!

**Comment by MichaelClerx** [comment]
Well OK, for this particular repo. But we had a lot of discussion 2 years ago about the best way forward (e.g. sandboxed python scripts etc.) that we put off until WL1 parity. After the workshop I think we're ready to pick all that up again!

**Comment by MichaelClerx** [comment]
Histograms are in now

**Pull request merged**
