### PR TITLE
Hacky version of fitting spec support

### LINKED ISSUE #182: Hacky support for fitting specs
- [x] Add a boolean field to `ProtocolEntity` (well, will probably have to be on `Entity` actually) stating that this is a fitting specification, not (just) a forward simulation protocol.
- [x] If this field is set, pass extra 'data' and 'fittingspec' arguments when launching experiments using this protocol.
- [x] On the experiments view, add a button to toggle between 'Show parameter fitting experiments' / 'Show simulation experiments' (which will add an extra boolean `show_fits` to the JSON call)
- [ ] Allow owners to toggle it on/off? Initially just require it to be set on entity creation.

### PR DESCRIPTION
**Pull request by jonc125**
Will fix #182.

Also includes aspects of #137, #131.

It is hacky and completely untested! We should consider what needs to be done to tidy this up before merge, or possibly post-merge to enable cleaner review.

Some clear outstanding tasks, which may become separate PRs, in rough priority order:
- [ ] Add tests for the new features, especially around data upload & view.
- [ ] Fix any bugs revealed!
    - [ ] For some reason the dataset description is not being set
- [ ] Respect dataset visibility - e.g. at present anyone can overlay other users' private datasets. Possibly they can link their data to private protocols as well; I'm not sure.
- [ ] Link fitting specs to datasets (and via that to a protocol) so a 'fitting spec' protocol only contains the actual fitting specification. We definitely don't want to do that as part of this PR. It may get subsumed by longer term planning for how this will be architected, e.g. when `FittingSpec` becomes a concept in its own right.

### CODE REVIEW

**Comment by jonc125** [comment]
Added another issue I spotted to the description.

**Comment by skeating** [comment]
Currently the description is part of the file upload page. This is inconsistent with 'description' for other files upload which is on the creation page. It is probably an easier fix to move the field :-)

**Comment by jonc125** [comment]
> Currently the description is part of the file upload page. This is inconsistent with 'description' for other files upload which is on the creation page. It is probably an easier fix to move the field :-)

Fine by me!

**Comment by jonc125** [comment]
I'm merging this to master so it can be deployed on scrambler and stop it being broken!

**Pull request merged**
