### PR TITLE
Model and protocol entities

### PR DESCRIPTION
**Pull request by helenst**
Allows creation of entities, and adding of new versions. Creates a git repository backing each entity, with each new version represented by a commit (optionally tagged).

(If you've run this code at any point during the branch's development, it is probably worth running `python manage.py migrate entities zero` before updating the branch and then re-running the full set of migrations from scratch.)

### CODE REVIEW

**Comment by jonc125** [comment]
I've not had a chance to review the code properly (although I have skimmed through the tests). I did have a play with the functionality though, and it's looking nice. There are a few issues I spotted, some minor and some more critical. I'll defer the minor ones to new issues, but I think it'd be good to fix the list below before merging.

- [ ] When adding a new version you can't see existing files (granted, that matches the current system, but we want to improve this :) )
- [ ] This compounds the problem that uploading a file with the same name as one already there gives an unfriendly error:
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/entities/models/1/versions/new

Django Version: 1.11.4
Python Version: 3.5.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'social_django',
 'accounts.apps.AccountsConfig',
 'entities.apps.EntitiesConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/shutil.py" in move
  544.         os.rename(src, real_dst)

During handling of the above exception ([Errno 2] No such file or directory: '/Users/jonc/projects/WebLab/WebLab/weblab/media/uploads/beeler_reuter_model_1977.cellml' -> '/Users/jonc/projects/WebLab/WebLab/weblab/repositories/1/models/1/beeler_reuter_model_1977.cellml'), another exception occurred:

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/contrib/auth/mixins.py" in dispatch
  56.         return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/contrib/auth/mixins.py" in dispatch
  92.         return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/Users/jonc/projects/WebLab/WebLab/weblab/entities/views.py" in post
  142.             shutil.move(src, dest)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/shutil.py" in move
  558.             copy_function(src, real_dst)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/shutil.py" in copy2
  257.     copyfile(src, dst, follow_symlinks=follow_symlinks)

File "/Users/jonc/anaconda3/envs/weblab/lib/python3.5/shutil.py" in copyfile
  120.         with open(src, 'rb') as fsrc:

Exception Type: FileNotFoundError at /entities/models/1/versions/new
Exception Value: [Errno 2] No such file or directory: '/Users/jonc/projects/WebLab/WebLab/weblab/media/uploads/beeler_reuter_model_1977.cellml'
```

**Comment by MichaelClerx** [comment]
I'm missing docstrings (file and class level, at the minimum) in these files!

**Comment by jonc125** [comment]
Yeah, brief docstrings could be useful. What might be best is for @helenst & I to write some orientation documentation together, giving the high-level overview particularly to help those not familiar with how Django structures things. I think for the most part the role of each file, class, etc. is 'obvious' from the naming for Django aficionados :)

**Comment by helenst** [comment]
OK... I've added existing files into the new version page and added checks against those files when detecting duplicates...

**Comment by jonc125** [comment]
That seems to be working nicely for me!

I think that means that except for documentation everything on this PR is either done or deferred to another issue. We could create a separate issue for documentation too and merge this?

**Comment by helenst** [comment]
As far as I am concerned, this is done and I'm moving onto other issues. I'll create one for the documentation.

**Pull request merged**
